# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='English_LearningOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_text', models.TextField(max_length=500)),
                ('skill', models.CharField(choices=[('Listening', 'Listening and Understanding'), ('Speaking', 'Speaking'), ('Reading', 'Reading and Thinking'), ('Writing Transcription', 'Writing Transcription'), ('Writing Composition', 'Writing Composition'), ('Writing Comprehension', 'Writing Comprehension'), ('Writing Grammer', 'Writing Grammer'), ('Creative Writing', 'Creative Writing'), ('Language Cognition', 'Language Cognition'), ('The Life Skills', 'The Life Skills')], default='Listening', max_length=16)),
                ('grade', models.CharField(choices=[('Grade-1', 'Grade-1'), ('Grade-2', 'Grade-2'), ('Grade-3', 'Grade-3'), ('Grade-4', 'Grade-4'), ('Grade-5', 'Grade-5')], default='Grade-1', max_length=16)),
                ('midterm_exploratory', models.IntegerField(default=1)),
                ('midterm_confirmatory', models.IntegerField(default=1)),
                ('final_exploratory', models.IntegerField(default=2)),
                ('final_confirmatory', models.IntegerField(default=2)),
                ('outcome_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'English Learning Outcome',
            },
        ),
        migrations.CreateModel(
            name='English_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=500)),
                ('type', models.CharField(choices=[('Confirmatory', 'Confirmatory'), ('Exploratory', 'Exploratory')], default='Confirmatory', max_length=16)),
                ('duration', models.CharField(choices=[('Long', 'Long'), ('Medium', 'Medium'), ('Short', 'Short')], default='Medium', max_length=16)),
                ('qimage', models.ImageField(blank=True, upload_to='english')),
                ('correct_answer', models.CharField(default='', max_length=200)),
                ('question_verified', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_author', models.CharField(default='Admin', max_length=16)),
                ('learnig_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efs.English_LearningOutcome')),
            ],
            options={
                'verbose_name': 'English Question',
            },
        ),
        migrations.CreateModel(
            name='Math_LearningOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_text', models.TextField(max_length=500)),
                ('skill', models.CharField(choices=[('Using and Applying Mathamatics', 'Using and Applying Mathamatics'), ('Counting and Number Relationship', 'Counting and Number Relationship'), ('Number Facts', 'Number Facts'), ('Calculations', 'Calculations'), ('Geomatry', 'Geomatry'), ('Measure', 'Measure'), ('Data Handling', 'Data Handling')], default='Using and Applying Mathamatics', max_length=16)),
                ('grade', models.CharField(choices=[('Grade-1', 'Grade-1'), ('Grade-2', 'Grade-2'), ('Grade-3', 'Grade-3'), ('Grade-4', 'Grade-4'), ('Grade-5', 'Grade-5')], default='Grade-1', max_length=16)),
                ('midterm_exploratory', models.IntegerField(default=1)),
                ('midterm_confirmatory', models.IntegerField(default=1)),
                ('final_exploratory', models.IntegerField(default=2)),
                ('final_confirmatory', models.IntegerField(default=2)),
                ('outcome_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Math Learning Outcome',
            },
        ),
        migrations.CreateModel(
            name='Math_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=500)),
                ('type', models.CharField(choices=[('Confirmatory', 'Confirmatory'), ('Exploratory', 'Exploratory')], default='Confirmatory', max_length=16)),
                ('duration', models.CharField(choices=[('Long', 'Long'), ('Medium', 'Medium'), ('Short', 'Short')], default='Medium', max_length=16)),
                ('qimage', models.ImageField(blank=True, upload_to='math')),
                ('correct_answer', models.CharField(default='', max_length=200)),
                ('question_verified', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_author', models.CharField(default='Admin', max_length=16)),
                ('learnig_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efs.Math_LearningOutcome')),
            ],
            options={
                'verbose_name': 'Math Question',
            },
        ),
        migrations.CreateModel(
            name='Sindhi_LearningOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_text', models.TextField(max_length=500)),
                ('skill', models.CharField(choices=[('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Reading', 'Reading'), ('Writing', 'Writing'), ('Creative Writing', 'Creative Writing'), ('Language Cognition', 'Language Cognition'), ('The Life Skills', 'The Life Skills'), ('Speech', 'Speech')], default='Listening', max_length=16)),
                ('grade', models.CharField(choices=[('Grade-1', 'Grade-1'), ('Grade-2', 'Grade-2'), ('Grade-3', 'Grade-3'), ('Grade-4', 'Grade-4'), ('Grade-5', 'Grade-5')], default='Grade-1', max_length=16)),
                ('midterm_exploratory', models.IntegerField(default=1)),
                ('midterm_confirmatory', models.IntegerField(default=1)),
                ('final_exploratory', models.IntegerField(default=2)),
                ('final_confirmatory', models.IntegerField(default=2)),
                ('outcome_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sindhi Learning Outcome',
            },
        ),
        migrations.CreateModel(
            name='Sindhi_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=500)),
                ('type', models.CharField(choices=[('Confirmatory', 'Confirmatory'), ('Exploratory', 'Exploratory')], default='Confirmatory', max_length=16)),
                ('duration', models.CharField(choices=[('Long', 'Long'), ('Medium', 'Medium'), ('Short', 'Short')], default='Medium', max_length=16)),
                ('qimage', models.ImageField(blank=True, upload_to='sindhi')),
                ('correct_answer', models.CharField(default='', max_length=200)),
                ('question_verified', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_author', models.CharField(default='Admin', max_length=16)),
                ('learnig_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efs.Sindhi_LearningOutcome')),
            ],
            options={
                'verbose_name': 'Sindhi Question',
            },
        ),
        migrations.CreateModel(
            name='Urdu_LearningOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_text', models.TextField(max_length=500)),
                ('skill', models.CharField(choices=[('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Reading', 'Reading'), ('Writing', 'Writing'), ('Creative Writing', 'Creative Writing'), ('Language Cognition', 'Language Cognition'), ('The Life Skills', 'The Life Skills'), ('Speech', 'Speech')], default='Listening', max_length=16)),
                ('grade', models.CharField(choices=[('Grade-1', 'Grade-1'), ('Grade-2', 'Grade-2'), ('Grade-3', 'Grade-3'), ('Grade-4', 'Grade-4'), ('Grade-5', 'Grade-5')], default='Grade-1', max_length=16)),
                ('midterm_exploratory', models.IntegerField(default=1)),
                ('midterm_confirmatory', models.IntegerField(default=1)),
                ('final_exploratory', models.IntegerField(default=2)),
                ('final_confirmatory', models.IntegerField(default=2)),
                ('outcome_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Urdu Learning Outcome',
            },
        ),
        migrations.CreateModel(
            name='Urdu_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=500)),
                ('type', models.CharField(choices=[('Confirmatory', 'Confirmatory'), ('Exploratory', 'Exploratory')], default='Confirmatory', max_length=16)),
                ('duration', models.CharField(choices=[('Long', 'Long'), ('Medium', 'Medium'), ('Short', 'Short')], default='Medium', max_length=16)),
                ('qimage', models.ImageField(blank=True, upload_to='sindhi')),
                ('correct_answer', models.CharField(default='', max_length=200)),
                ('question_verified', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_author', models.CharField(default='Admin', max_length=16)),
                ('learnig_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efs.Urdu_LearningOutcome')),
            ],
            options={
                'verbose_name': 'Urdu Question',
            },
        ),
    ]
